name: gogo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.5
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  email_validator: ^2.1.17
  image_picker: ^1.0.4
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.3.0
  google_maps_flutter_web: ^0.5.4+1
  uuid: ^4.0.0
  intl: ^0.18.1
  smooth_star_rating: ^1.1.1
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/screen.png
    - assets/images/paris.png
    - assets/images/attraction.png
    - assets/images/beauty.png
    - assets/images/boba.png
    - assets/images/coffee.png
    - assets/images/flight.png
    - assets/images/google.png
    - assets/images/museum.png
    - assets/images/nature.png
    - assets/images/paris.png
    - assets/images/religious.png
    - assets/images/restaurant.png
    - assets/images/screen.png
    - assets/images/shopping.png
    - assets/images/sports.png
    - assets/images/vietnam.png
    - assets/images/avatar.png
    - assets/images/venice.png
    - assets/images/la.png
