// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdmZIdF5j__7yrx9__RRoyYARUfOOKho',
    appId: '1:782645075313:web:82b8b02dd5f3988a0f2ad0',
    messagingSenderId: '782645075313',
    projectId: 'gogo-fe2c0',
    authDomain: 'gogo-fe2c0.firebaseapp.com',
    storageBucket: 'gogo-fe2c0.appspot.com',
    measurementId: 'G-V8CLKMV7JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRDfKaneOabWP76QDQfj9QUDVzXWHDh3g',
    appId: '1:782645075313:android:104d4969585077780f2ad0',
    messagingSenderId: '782645075313',
    projectId: 'gogo-fe2c0',
    storageBucket: 'gogo-fe2c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8Fy6oDemh4se7nv2u-asuSnUi15sQeU',
    appId: '1:782645075313:ios:814ae4e22e167deb0f2ad0',
    messagingSenderId: '782645075313',
    projectId: 'gogo-fe2c0',
    storageBucket: 'gogo-fe2c0.appspot.com',
    iosBundleId: 'com.example.gogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8Fy6oDemh4se7nv2u-asuSnUi15sQeU',
    appId: '1:782645075313:ios:814ae4e22e167deb0f2ad0',
    messagingSenderId: '782645075313',
    projectId: 'gogo-fe2c0',
    storageBucket: 'gogo-fe2c0.appspot.com',
    iosBundleId: 'com.example.gogo',
  );
}
